### ISSUE TITLE
Adding a backup pool in progminer

### ISSUE THREAD

**Issue by rgzrgz** [gangnamtestnet/progminer#1]
I'm always frustrated when pool is disconnected. I've tried but I miss one feature: failover pools.

I really look forward to the function of the failover pool.

it would be really nice to have failover for pools in pools.txt file like Claymore's dual miner or Phoenixminer.

it should be in a separate file "failover.txt", because it's fairly common practice in the mining software development.

Command line arguments (.bat file) must be always override the default JSON configuration.

**Comment by naikmyeong** [comment]
@rgzrgz Progpool is based on the latest branch of Ethminer and I assume it is possible to define a backup pool by adding more pools on the option

For example

`progminer  -U -P stratum://0xb85150eb365e7df0941f0cf08235f987ba91506a/myfarm@testnet.progpool.pro:8008 -P stratum://0xb85150eb365e7df0941f0cf08235f987ba91506a/myfarm@testnet2.progpool.pro:8008`
