### ISSUE TITLE
Windows 10 64

### ISSUE THREAD

**Issue by gennadiv** [gangnamtestnet/progminer#24]
https://pastenow.ru/4JJVJ         AMD GPU
progminer 1.1.0

**Comment by naikmyeong** [comment]
@gennadiv Progminer doesn't support ethash mining pools

**Comment by gennadiv** [comment]
1.1.1  you still cooking ? and the in releases his there is no

**Comment by naikmyeong** [comment]
Please use appropriate english, and 1.1.1 is our next release with bug fixes
