### ISSUE TITLE
ProgMiner doesn't detect RX570 mining rig

### ISSUE THREAD

**Issue by SillaceMiningInc** [gangnamtestnet/progminer#25]
When trying to start progminer for testnet I get the response that Unrecognized platform Intel(R) OpenCL.  Error: No usable mining devices found. 

This is a 7x RX 570 rig that works fine on ETH using claymore.  219Mh/s stable.

I have tried multiple arguments and still no luck.  Searched Google and forums as well as BBT Discord and didn't find any results that showed similar problem.

I did not find any directions on the help file for this release either.  Tried 1.1.0 amd windows amd64 as well as 1.0.2-amd-windows version.

Rig runs intel celeron cpu and display is off of integrated graphics while 7x 570s do the mining work.  Strange that they aren't detected.

**Comment by naikmyeong** [comment]
Have you tried downloading amd version?

**Comment by naikmyeong** [comment]
Ok, this is wierd, can you post some screenshots if not bother?

**Comment by jean-m-cyr** [comment]
What command line are you using?

**Comment by SillaceMiningInc** [comment]
Works fine on Claymore for ETH 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/34257074/51419370-f0594e00-1b57-11e9-9010-71fe5bc2433c.png)

**Comment by naikmyeong** [comment]
@SillaceMiningInc Can you try with ethminer? https://github.com/ethereum-mining/ethminer/releases/tag/v0.18.0-alpha.3 Progminer is based on ethminer and I don't think opencl device detection is the problem from progminer.

**Comment by SillaceMiningInc** [comment]
Same problem with ethminer.  below is a screenshot showing I have the devices registered in Windows but when the --list-devices command is added to arguments it shows no usable mining devices just like ProgMiner.  I am sort of stumped....
![image](https://user-images.githubusercontent.com/34257074/51432086-dc692700-1bff-11e9-9144-b216abe10d5b.png)

**Comment by naikmyeong** [comment]
@SillaceMiningInc I see, I would recommend you to create an issue on their repository too https://github.com/ethereum-mining/ethminer/issues , since it will be more productive to have a fix on both sides.
