### ISSUE TITLE
Tools dont run

### ISSUE THREAD

**Issue by lambhiu** [gangnamtestnet/progminer#26]
Window 10 ltsc
Error 
the application was unable to start correctly 0x000007b
Image: https://sv1.uphinhnhanh.com/images/2019/01/18/9376E23E-4D38-4827-8444-86378C51ECED.png

**Comment by naikmyeong** [comment]
@lambhiu Yes they are .dll dependency errors, can you tell your CUDA version and your mining cards?

**Comment by naikmyeong** [comment]
Same with https://github.com/gangnamtestnet/progminer/issues/31 use 1.1.1-opencl version instead of 1.1.1
