### ISSUE TITLE
Progminer doesn't work for BCI pools ( rejected share for mining )

### ISSUE THREAD

**Issue by aleqx** [gangnamtestnet/progminer#9]
I take it that ProgPow 0.9.2+ is incompatible with the ProgPow version used in Bitcoin Interest, is that true? Is that true (it's not said anywhere, unless I missed it).

I'm getting only rejected shares on all BCI pools I tried. 

` X 03:10:28 miner    GPU 3 gave incorrect result. Lower overclocking values if it happens frequently.`

All GPUs say that, for every submitted share.

It also rejects `miner.set_target` so it doesn't seem to talk the same protocol:

` X 03:09:42 miner    Got unknown method [mining.set_target] from pool. Discarding...`

**Comment by naikmyeong** [comment]
Progminer doesn't work for BCI or Bitcoin-based coins with ProgPoW implementation, we tend to develop and maintain Progminer for ethereum-based networks.

**Comment by naikmyeong** [comment]
Will leave this issue open since many people confuse about BCI's ProgPoW and Ethereum ProgPoW

**Comment by aleqx** [comment]
That's what I thought. if I were you I would make a clear note about this in the project description, rather than leave it (almost hidden) here.

**Comment by naikmyeong** [comment]
@aleqx I just thought about that and will do, thanks for your advice 👍

**Comment by naikmyeong** [comment]
Fixed on https://github.com/gangnamtestnet/progminer/commit/020de054c7fde67fbe4f265058fb015d36f39610
